server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # SPA — todas las rutas al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy al backend Django
    location /api/ {
        proxy_pass         http://web:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Admin de Django (opcional)
    location /admin/ {
        proxy_pass         http://web:8000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    # Estáticos de Django (admin CSS/JS)
    location /static/ {
        proxy_pass http://web:8000;
    }
}