# Generated by Django 5.1.4 on 2026-04-01 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_sistemaoperativo_software_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta', models.CharField(help_text='Generado automaticamente (formato: ACTA-YYYYMMDD-XXXX).', max_length=50, unique=True, verbose_name='Numero de acta')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del equipo')),
                ('tipo_acta', models.CharField(choices=[('entrega', 'Entrega de Equipo'), ('devolucion', 'Devolucion de Equipo'), ('cambio', 'Cambio de Equipo')], default='entrega', max_length=20, verbose_name='Tipo de acta')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_firma', 'Pendiente de Firma'), ('firmada', 'Firmada'), ('anulada', 'Anulada')], default='pendiente_firma', max_length=20, verbose_name='Estado del acta')),
                ('detalle_equipo', models.JSONField(blank=True, default=dict, help_text='Snapshot de las specs del equipo al momento de la entrega.', verbose_name='Detalle del equipo')),
                ('observaciones', models.TextField(blank=True, default='', help_text='Estado fisico del equipo, accesorios entregados, etc.', verbose_name='Observaciones')),
                ('accesorios', models.TextField(blank=True, default='', help_text='Cargador, mouse, maletin, etc.', verbose_name='Accesorios entregados')),
                ('condiciones_uso', models.TextField(blank=True, default='El empleado se compromete a utilizar el equipo entregado exclusivamente para actividades laborales, a mantenerlo en buen estado y a reportar cualquier dano o perdida de manera inmediata al area de TI.', verbose_name='Condiciones de uso')),
                ('firma_empleado_imagen', models.TextField(blank=True, default='', help_text='Imagen de la firma capturada desde un canvas en el frontend.', verbose_name='Firma del empleado (base64)')),
                ('firma_responsable_imagen', models.TextField(blank=True, default='', verbose_name='Firma del responsable TI (base64)')),
                ('firma_digital_hash', models.CharField(blank=True, default='', help_text='Hash SHA-256 del documento firmado digitalmente.', max_length=512, verbose_name='Hash de firma digital')),
                ('certificado_serial', models.CharField(blank=True, default='', max_length=255, verbose_name='Serial del certificado')),
                ('firma_digital_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp de la firma digital')),
                ('firma_digital_valida', models.BooleanField(default=False, verbose_name='Firma digital valida')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='actas/pdf/%Y/%m/', verbose_name='Archivo PDF')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_firma', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de firma')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('computador', 'celular', 'monitor')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de equipo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actas_entrega', to='inventory.empleado', verbose_name='Empleado receptor')),
                ('responsable_ti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas_gestionadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable TI')),
            ],
            options={
                'verbose_name': 'Acta de entrega',
                'verbose_name_plural': 'Actas de entrega',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['-fecha_creacion'], name='actas_actae_fecha_c_b89777_idx'), models.Index(fields=['numero_acta'], name='actas_actae_numero__ca9944_idx'), models.Index(fields=['estado'], name='actas_actae_estado_7d7404_idx'), models.Index(fields=['empleado'], name='actas_actae_emplead_924adf_idx')],
            },
        ),
    ]
