# Generated by Django 5.1.4 on 2026-04-08 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaentrega',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('computador', 'celular', 'monitor', 'chip')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de equipo'),
        ),
    ]
