# Generated by Django 5.1.4 on 2026-03-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('ACTUALIZACION', 'Actualización'), ('ELIMINACION', 'Eliminación'), ('CAMBIO_ESTADO', 'Cambio de Estado')], max_length=20, verbose_name='Acción')),
                ('campo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Campo modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuario')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
            ],
            options={
                'verbose_name': 'Registro de cambio',
                'verbose_name_plural': 'Registros de cambios',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='auditlog_re_fecha_3bb02f_idx'), models.Index(fields=['content_type', 'object_id'], name='auditlog_re_content_951958_idx'), models.Index(fields=['accion'], name='auditlog_re_accion_7c018d_idx')],
            },
        ),
    ]
