# Generated by Django 5.1.4 on 2026-04-01 17:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Sistema operativo')),
            ],
            options={
                'verbose_name': 'Sistema operativo',
                'verbose_name_plural': 'Sistemas operativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del software')),
                ('fabricante', models.CharField(blank=True, default='', max_length=100, verbose_name='Fabricante')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='almacenamiento',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='empleado_asignado',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='procesador',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='ram',
        ),
        migrations.AlterModelOptions(
            name='almacenamiento',
            options={'ordering': ['tipo', 'capacidad'], 'verbose_name': 'Almacenamiento', 'verbose_name_plural': 'Almacenamientos'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['nombre'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
        migrations.AddField(
            model_name='almacenamiento',
            name='nombre_modelo',
            field=models.CharField(blank=True, help_text='Modelo exacto del disco (ej: Samsung 970 EVO Plus).', max_length=150, null=True, verbose_name='Modelo del disco'),
        ),
        migrations.AddField(
            model_name='almacenamiento',
            name='tipo',
            field=models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('NVME', 'NVMe'), ('EMMC', 'eMMC')], default='SSD', max_length=10, verbose_name='Tipo de almacenamiento'),
        ),
        migrations.AddField(
            model_name='celular',
            name='numero_linea',
            field=models.CharField(blank=True, help_text='Numero telefonico de la linea asignada.', max_length=20, null=True, unique=True, verbose_name='Numero de linea'),
        ),
        migrations.AddField(
            model_name='celular',
            name='tipo_equipo',
            field=models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('TABLET', 'Tablet')], default='SMARTPHONE', max_length=15, verbose_name='Tipo de equipo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_desactivacion',
            field=models.DateField(blank=True, help_text='Fecha en que el empleado fue marcado como inactivo.', null=True, verbose_name='Fecha de desactivacion'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='givenName de Active Directory.', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='sn (surname) de Active Directory.', max_length=100, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ldap_dn',
            field=models.TextField(blank=True, default='', help_text='DN completo en AD, util para saber la OU.', verbose_name='Distinguished Name (AD)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ldap_object_guid',
            field=models.CharField(blank=True, help_text='Identificador permanente en Active Directory. Nunca cambia aunque el usuario sea renombrado o movido.', max_length=40, null=True, unique=True, verbose_name='objectGUID (AD)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Cedula de identidad (C.C.) - identificador de RR.HH.', max_length=20, null=True, unique=True, verbose_name='Numero de documento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Vincula al empleado con su cuenta Django. Opcional: empleados de terreno pueden no tener cuenta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='username',
            field=models.CharField(blank=True, help_text='sAMAccountName de Active Directory.', max_length=150, null=True, unique=True, verbose_name='Username (AD)'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='numero_linea',
            field=models.CharField(blank=True, db_index=True, help_text='Numero telefonico de la linea asignada.', max_length=20, null=True, verbose_name='Numero de linea'),
        ),
        migrations.AddField(
            model_name='historicalcelular',
            name='tipo_equipo',
            field=models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('TABLET', 'Tablet')], default='SMARTPHONE', max_length=15, verbose_name='Tipo de equipo'),
        ),
        migrations.AddField(
            model_name='ram',
            name='part_number',
            field=models.CharField(blank=True, help_text='P/N del fabricante del modulo de RAM.', max_length=100, null=True, verbose_name='Part Number'),
        ),
        migrations.AlterField(
            model_name='almacenamiento',
            name='capacidad',
            field=models.CharField(help_text='Ejemplo: 256GB, 1TB, 512GB', max_length=100, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del area'),
        ),
        migrations.AlterField(
            model_name='celular',
            name='almacenamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='celulares', to='inventory.almacenamiento', verbose_name='Almacenamiento'),
        ),
        migrations.AlterField(
            model_name='celular',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, help_text='Dejar en blanco si el equipo esta en bodega.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='celulares', to='inventory.empleado', verbose_name='Empleado asignado'),
        ),
        migrations.AlterField(
            model_name='celular',
            name='estado',
            field=models.CharField(choices=[('EN_USO', 'En Uso'), ('EN_BODEGA', 'En Bodega'), ('EN_REPARACION', 'En Reparacion'), ('PENDIENTE_DEVOLUCION', 'Pendiente Devolucion'), ('DE_BAJA', 'De Baja')], default='EN_BODEGA', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='celular',
            name='imei',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='celular',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numero de serie'),
        ),
        migrations.AlterField(
            model_name='celular',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='celulares', to='inventory.ram', verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarque si el empleado ya no trabaja en la empresa.', verbose_name='Empleado activo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='inventory.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Cargo o puesto'),
        ),
        migrations.AlterField(
            model_name='historicalcelular',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Dejar en blanco si el equipo esta en bodega.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.empleado', verbose_name='Empleado asignado'),
        ),
        migrations.AlterField(
            model_name='historicalcelular',
            name='estado',
            field=models.CharField(choices=[('EN_USO', 'En Uso'), ('EN_BODEGA', 'En Bodega'), ('EN_REPARACION', 'En Reparacion'), ('PENDIENTE_DEVOLUCION', 'Pendiente Devolucion'), ('DE_BAJA', 'De Baja')], default='EN_BODEGA', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalcelular',
            name='imei',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='IMEI'),
        ),
        migrations.AlterField(
            model_name='historicalcelular',
            name='numero_serie',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Numero de serie'),
        ),
        migrations.AlterUniqueTogether(
            name='almacenamiento',
            unique_together={('tipo', 'capacidad')},
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventario', models.CharField(help_text='Identificador fisico del activo (ej: ELEQ-1600).', max_length=50, unique=True, verbose_name='Numero de inventario')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Numero de serie')),
                ('tipo_equipo', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('ALL_IN_ONE', 'All-in-One'), ('WORKSTATION', 'Workstation')], default='LAPTOP', max_length=20, verbose_name='Tipo de equipo')),
                ('numero_sticks_ram', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de modulos RAM')),
                ('estado', models.CharField(choices=[('EN_USO', 'En Uso'), ('EN_BODEGA', 'En Bodega'), ('EN_REPARACION', 'En Reparacion'), ('PENDIENTE_DEVOLUCION', 'Pendiente Devolucion'), ('DE_BAJA', 'De Baja')], default='EN_BODEGA', max_length=25, verbose_name='Estado')),
                ('en_inventario', models.BooleanField(default=True, help_text='Indica si el equipo esta fisicamente en las instalaciones. Un equipo puede estar EN_USO pero no en inventario (en obra).', verbose_name='En inventario')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('accesorios', models.TextField(blank=True, default='', help_text='Cargador, mouse, maletin, etc.', verbose_name='Accesorios')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='Comentario')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('almacenamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computadores', to='inventory.almacenamiento', verbose_name='Almacenamiento')),
                ('empleado_asignado', models.ForeignKey(blank=True, help_text='Dejar en blanco si el equipo esta en bodega.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computadores', to='inventory.empleado', verbose_name='Empleado asignado')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computadores', to='inventory.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computadores', to='inventory.modelo', verbose_name='Modelo')),
                ('procesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computadores', to='inventory.procesador', verbose_name='Procesador')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computadores', to='inventory.ram', verbose_name='RAM')),
                ('sistema_operativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computadores', to='inventory.sistemaoperativo', verbose_name='Sistema operativo')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventario', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numero de inventario')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numero de serie')),
                ('estado', models.CharField(choices=[('EN_USO', 'En Uso'), ('EN_BODEGA', 'En Bodega'), ('EN_REPARACION', 'En Reparacion'), ('PENDIENTE_DEVOLUCION', 'Pendiente Devolucion'), ('DE_BAJA', 'De Baja')], default='EN_BODEGA', max_length=25, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('computador', models.ForeignKey(blank=True, help_text='Equipo al que esta fisicamente conectado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitores', to='inventory.computador', verbose_name='Computador conectado')),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitores', to='inventory.empleado', verbose_name='Empleado asignado')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitores', to='inventory.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitores', to='inventory.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalComputador',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_inventario', models.CharField(db_index=True, help_text='Identificador fisico del activo (ej: ELEQ-1600).', max_length=50, verbose_name='Numero de inventario')),
                ('numero_serie', models.CharField(db_index=True, max_length=100, verbose_name='Numero de serie')),
                ('tipo_equipo', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('ALL_IN_ONE', 'All-in-One'), ('WORKSTATION', 'Workstation')], default='LAPTOP', max_length=20, verbose_name='Tipo de equipo')),
                ('numero_sticks_ram', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de modulos RAM')),
                ('estado', models.CharField(choices=[('EN_USO', 'En Uso'), ('EN_BODEGA', 'En Bodega'), ('EN_REPARACION', 'En Reparacion'), ('PENDIENTE_DEVOLUCION', 'Pendiente Devolucion'), ('DE_BAJA', 'De Baja')], default='EN_BODEGA', max_length=25, verbose_name='Estado')),
                ('en_inventario', models.BooleanField(default=True, help_text='Indica si el equipo esta fisicamente en las instalaciones. Un equipo puede estar EN_USO pero no en inventario (en obra).', verbose_name='En inventario')),
                ('fecha_ingreso', models.DateField(blank=True, editable=False, verbose_name='Fecha de ingreso')),
                ('accesorios', models.TextField(blank=True, default='', help_text='Cargador, mouse, maletin, etc.', verbose_name='Accesorios')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='Comentario')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('almacenamiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.almacenamiento', verbose_name='Almacenamiento')),
                ('empleado_asignado', models.ForeignKey(blank=True, db_constraint=False, help_text='Dejar en blanco si el equipo esta en bodega.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.empleado', verbose_name='Empleado asignado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.modelo', verbose_name='Modelo')),
                ('procesador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.procesador', verbose_name='Procesador')),
                ('ram', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.ram', verbose_name='RAM')),
                ('sistema_operativo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.sistemaoperativo', verbose_name='Sistema operativo')),
            ],
            options={
                'verbose_name': 'historical Computador',
                'verbose_name_plural': 'historical Computadores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ComputadorSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='Version')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de instalacion')),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_instalado', to='inventory.computador', verbose_name='Computador')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='inventory.software', verbose_name='Software')),
            ],
            options={
                'verbose_name': 'Software instalado',
                'verbose_name_plural': 'Software instalado',
                'ordering': ['software__nombre'],
                'unique_together': {('computador', 'software')},
            },
        ),
        migrations.DeleteModel(
            name='HistoricalLaptop',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
