# Generated by Django 5.1.4 on 2026-04-08 21:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sistemaoperativo_software_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='ldap_ou_dn',
            field=models.TextField(blank=True, default='', help_text='DN completo de la OU en Active Directory. Se llena automaticamente.', verbose_name='OU Distinguished Name (AD)'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, help_text='Opcional. Se registra en la app al enviar el primer acta. No se sincroniza desde Active Directory.', max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Se asigna automáticamente según la OU de Active Directory.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='inventory.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, default='', help_text='Se ingresa manualmente en la app. No se sincroniza desde AD.', max_length=150, verbose_name='Cargo o puesto'),
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: CC-ILU-001', max_length=30, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / Descripción de la obra')),
                ('tipo', models.CharField(choices=[('LINEA', 'Línea de Transmisión'), ('SUBESTACION', 'Subestación'), ('ADMINISTRACION', 'Administración'), ('OPERACION', 'Operación'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo de obra')),
                ('activo', models.BooleanField(default=True, help_text='Desmarque si la obra ya terminó.', verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_costo', to='inventory.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'ordering': ['area__nombre', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='centro_costo',
            field=models.ForeignKey(blank=True, help_text='Obra a la que se cargan los equipos asignados a este empleado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='inventory.centrocosto', verbose_name='Centro de Costo / Obra'),
        ),
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.CharField(help_text='Ej: 56987452398', max_length=20, unique=True, verbose_name='Número de línea')),
                ('operador', models.CharField(choices=[('ENTEL', 'Entel'), ('MOVISTAR', 'Movistar'), ('CLARO', 'Claro'), ('WOM', 'WOM'), ('OTRO', 'Otro')], default='ENTEL', max_length=20, verbose_name='Operador')),
                ('iccid', models.CharField(blank=True, help_text='Número físico impreso en el SIM (19-20 dígitos).', max_length=25, null=True, unique=True, verbose_name='ICCID')),
                ('plan', models.CharField(blank=True, default='', help_text='Ej: Plan Empresas 10GB', max_length=150, verbose_name='Plan contratado')),
                ('estado', models.CharField(choices=[('EN_USO', 'En Uso'), ('EN_BODEGA', 'En Bodega'), ('SUSPENDIDA', 'Línea Suspendida'), ('DE_BAJA', 'De Baja')], default='EN_BODEGA', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('celular', models.ForeignKey(blank=True, help_text='Opcional. Dejar vacío si el chip está en bodega o se entrega solo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chips', to='inventory.celular', verbose_name='Teléfono donde está insertado')),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chips', to='inventory.empleado', verbose_name='Empleado asignado')),
            ],
            options={
                'verbose_name': 'Chip / SIM',
                'verbose_name_plural': 'Chips / SIMs',
                'ordering': ['operador', 'numero_linea'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCentroCosto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Ej: CC-ILU-001', max_length=30, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre / Descripción de la obra')),
                ('tipo', models.CharField(choices=[('LINEA', 'Línea de Transmisión'), ('SUBESTACION', 'Subestación'), ('ADMINISTRACION', 'Administración'), ('OPERACION', 'Operación'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo de obra')),
                ('activo', models.BooleanField(default=True, help_text='Desmarque si la obra ya terminó.', verbose_name='Activo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.area', verbose_name='Área')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Centro de Costo',
                'verbose_name_plural': 'historical Centros de Costo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalChip',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_linea', models.CharField(db_index=True, help_text='Ej: 56987452398', max_length=20, verbose_name='Número de línea')),
                ('operador', models.CharField(choices=[('ENTEL', 'Entel'), ('MOVISTAR', 'Movistar'), ('CLARO', 'Claro'), ('WOM', 'WOM'), ('OTRO', 'Otro')], default='ENTEL', max_length=20, verbose_name='Operador')),
                ('iccid', models.CharField(blank=True, db_index=True, help_text='Número físico impreso en el SIM (19-20 dígitos).', max_length=25, null=True, verbose_name='ICCID')),
                ('plan', models.CharField(blank=True, default='', help_text='Ej: Plan Empresas 10GB', max_length=150, verbose_name='Plan contratado')),
                ('estado', models.CharField(choices=[('EN_USO', 'En Uso'), ('EN_BODEGA', 'En Bodega'), ('SUSPENDIDA', 'Línea Suspendida'), ('DE_BAJA', 'De Baja')], default='EN_BODEGA', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateField(blank=True, editable=False, verbose_name='Fecha de ingreso')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('celular', models.ForeignKey(blank=True, db_constraint=False, help_text='Opcional. Dejar vacío si el chip está en bodega o se entrega solo.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.celular', verbose_name='Teléfono donde está insertado')),
                ('empleado_asignado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.empleado', verbose_name='Empleado asignado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Chip / SIM',
                'verbose_name_plural': 'historical Chips / SIMs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
