# Generated by Django 5.1.4 on 2026-04-14 14:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='centro_costo',
            field=models.ForeignKey(blank=True, help_text='Solo aplica para rol Encargado de Obra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_encargados', to='inventory.centrocosto', verbose_name='Centro de Costo asignado'),
        ),
        migrations.CreateModel(
            name='HistoricalSolicitudCorreo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALTA', 'Alta (crear correo)'), ('BAJA', 'Baja (eliminar correo)')], max_length=10, verbose_name='Tipo de solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO_CAU', 'Enviado a CAU'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('empleado_nombre', models.CharField(max_length=200, verbose_name='Nombre completo del empleado')),
                ('empleado_rut', models.CharField(help_text='Ej: 12.345.678-9', max_length=12, verbose_name='RUT del empleado')),
                ('empleado_cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('fecha_requerida', models.DateField(help_text='Fecha desde cuando necesita el correo (alta) o hasta cuando (baja).', verbose_name='Fecha requerida')),
                ('numero_ticket_cau', models.CharField(blank=True, default='', help_text='Número asignado por el CAU de España al enviar la solicitud.', max_length=50, verbose_name='N° Ticket CAU')),
                ('link_solicitud_cau', models.URLField(blank=True, default='', help_text='URL directa a la solicitud en el portal CAU de España.', max_length=500, verbose_name='Link solicitud CAU')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última modificación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('centro_costo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.centrocosto', verbose_name='Centro de Costo / Obra')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'historical Solicitud de correo',
                'verbose_name_plural': 'historical Solicitudes de correo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SolicitudCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ALTA', 'Alta (crear correo)'), ('BAJA', 'Baja (eliminar correo)')], max_length=10, verbose_name='Tipo de solicitud')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO_CAU', 'Enviado a CAU'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('empleado_nombre', models.CharField(max_length=200, verbose_name='Nombre completo del empleado')),
                ('empleado_rut', models.CharField(help_text='Ej: 12.345.678-9', max_length=12, verbose_name='RUT del empleado')),
                ('empleado_cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('fecha_requerida', models.DateField(help_text='Fecha desde cuando necesita el correo (alta) o hasta cuando (baja).', verbose_name='Fecha requerida')),
                ('numero_ticket_cau', models.CharField(blank=True, default='', help_text='Número asignado por el CAU de España al enviar la solicitud.', max_length=50, verbose_name='N° Ticket CAU')),
                ('link_solicitud_cau', models.URLField(blank=True, default='', help_text='URL directa a la solicitud en el portal CAU de España.', max_length=500, verbose_name='Link solicitud CAU')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_correo', to='inventory.centrocosto', verbose_name='Centro de Costo / Obra')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_correo', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Solicitud de correo',
                'verbose_name_plural': 'Solicitudes de correo',
                'ordering': ['-created_at'],
            },
        ),
    ]
