# Generated by Django 5.1.4 on 2026-04-01 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0002_sistemaoperativo_software_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del equipo')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20, verbose_name='Tipo de mantenimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(help_text='Detalle de la intervencion realizada o por realizar.', verbose_name='Descripcion del trabajo')),
                ('diagnostico', models.TextField(blank=True, default='', help_text='Problema identificado antes de la intervencion.', verbose_name='Diagnostico')),
                ('componentes_cambiados', models.TextField(blank=True, default='', help_text='Lista de piezas reemplazadas (ej: RAM 8GB -> 16GB, SSD 256GB -> 512GB).', verbose_name='Componentes cambiados')),
                ('actualizar_specs', models.BooleanField(default=False, help_text='Si es True, al completar el mantenimiento se actualizan las especificaciones del equipo (RAM, Almacenamiento, etc.).', verbose_name='Actualizar specs del equipo')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de repuestos')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo mano de obra')),
                ('proveedor_externo', models.CharField(blank=True, default='', help_text='Nombre del proveedor si el mantenimiento fue tercerizado.', max_length=200, verbose_name='Proveedor externo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio del trabajo')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalizacion')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas adicionales')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('computador', 'celular', 'monitor')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de equipo')),
                ('nueva_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_ram', to='inventory.ram', verbose_name='Nueva RAM (si aplica)')),
                ('nuevo_almacenamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_almacenamiento', to='inventory.almacenamiento', verbose_name='Nuevo almacenamiento (si aplica)')),
                ('nuevo_procesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_procesador', to='inventory.procesador', verbose_name='Nuevo procesador (si aplica)')),
                ('tecnico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Tecnico responsable')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='mantenimiento/archivos/%Y/%m/', verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('foto_antes', 'Foto antes'), ('foto_despues', 'Foto despues'), ('documento', 'Documento de soporte'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de archivo')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripcion')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='mantenimiento.mantenimiento', verbose_name='Mantenimiento')),
            ],
            options={
                'verbose_name': 'Archivo de mantenimiento',
                'verbose_name_plural': 'Archivos de mantenimiento',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['-fecha_creacion'], name='mantenimien_fecha_c_ffd684_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['content_type', 'object_id'], name='mantenimien_content_d91c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['tipo'], name='mantenimien_tipo_748397_idx'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['estado'], name='mantenimien_estado_1614ae_idx'),
        ),
    ]
